apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-cron
  labels:
    run: test-cron
spec:
  schedule: 0 * * * *
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            run: test-cron
        spec:
          restartPolicy: Never
          containers:
            - name: test
              imagePullPolicy: Always
              image: node
              command:
                - echo
                - HELLO WORLD
