apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: xpeppy/api.peppysisay.com:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8080"
            - name: GOOGLE_CREDENTIALS_TYPE
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: GOOGLE_CREDENTIALS_TYPE
            - name: GOOGLE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: GOOGLE_PROJECT_ID
            - name: GOOGLE_PRIVATE_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: GOOGLE_PRIVATE_KEY_ID
            - name: GOOGLE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: GOOGLE_PRIVATE_KEY
            - name: GOOGLE_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: GOOGLE_CLIENT_EMAIL
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_AUTH_URI
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: GOOGLE_AUTH_URI
            - name: GOOGLE_TOKEN_URI
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: GOOGLE_TOKEN_URI
            - name: GOOGLE_AUTH_PROVIDER_X509_CERT_URL
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: GOOGLE_AUTH_PROVIDER_X509_CERT_URL
            - name: GOOGLE_CLIENT_X509_CERT_URL
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: GOOGLE_CLIENT_X509_CERT_URL
